# Site settings

title: DOAG PL/SQL Conventions
 
tag_text: DOAG PL/SQL Conventions

description: A responsive template for publishing single-page websites, articles that are easy on the eyes

url: "http://127.0.0.1:4000"


# Build settings

markdown: kramdown

exclude: ["README.md"]
